# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gbx < Formula
  desc ""
  homepage ""
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/globalblackbox/gbx/releases/download/v0.1.3/gbx_0.1.3_darwin_amd64.tar.gz"
      sha256 "25ad6839dd0a83d147504d54812bb925f50bd89992d70c725651887f9945b24d"

      def install
        bin.install "gbx"
      end
    end
    on_arm do
      url "https://github.com/globalblackbox/gbx/releases/download/v0.1.3/gbx_0.1.3_darwin_arm64.tar.gz"
      sha256 "eb6837687bf984b31008af646cd6f468f960273299d6db34c09942156cb3049d"

      def install
        bin.install "gbx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/globalblackbox/gbx/releases/download/v0.1.3/gbx_0.1.3_linux_amd64.tar.gz"
        sha256 "0ba1f3beeefc9caf04bd6f3fdf54d38c79aa238a0a2606148295971d349dbe38"

        def install
          bin.install "gbx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/globalblackbox/gbx/releases/download/v0.1.3/gbx_0.1.3_linux_arm64.tar.gz"
        sha256 "dd75c8572fa0def8d6efabc100573a336370bbf49fe13e3807d1897a3c5e16fe"

        def install
          bin.install "gbx"
        end
      end
    end
  end
end
